import create from "zustand";
import {RegexTreeItem} from "@/analyze_regex/domain/models/regexTree";

interface AppState {
    /**
     * The user provided regex
     */
    regex: string|null,
    /**
     * Regex tree model generated by parseRegex from the user provided regex
     */
    regexModel: RegexTreeItem|null,
    /**
     * The zero-indexed step the user is at in the tutorial
     */
    solveStep: number,
}

const useAppStateStore = create<AppState>(() => ({
    regex: null,
    regexModel: null,
    solveStep: 0,
}))

export default useAppStateStore
